apiVersion: apps/v1
kind: Deployment
metadata:
  name: draft-simulator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: draft-simulator
  template:
    metadata:
      labels:
        app: draft-simulator
    spec:
      containers:
      - name: draft-simulator
        image: rpreet88/draft-simulator:latest
        ports:
        - containerPort: 5000