name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest  
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies - DraftSimulator
      run: dotnet restore
      working-directory: ./DraftSimulator
      
    - name: Build Project - DraftSimulator
      run: dotnet build
      working-directory: ./DraftSimulator

    # - name: Execute unit tests
    # run: dotnet test
